name: Test

on: push

jobs:
    versioning:
        name: Test
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - run: echo "VERSION=2012-dev" >> "$GITHUB_OUTPUT"
            - run: echo "${{ vars.VERSION }}"
            
            # - name: Another test
            #   uses: actions/github-script@v6
            #   with:
            #     script: |
            #         let data = '';
                    
            #         const options = {
            #           listeners: {
            #             stdout: (d) => {
            #               data += d.toString();
            #             },
            #           },
            #         };
                    
            #         await exec.exec('ls', [], options);
                    
            #         const result = data
            #           .split('\n')
            #           .filter(Boolean)
            #           .map((dir) => ({ name: dir }));
                    
            #         console.log(result);
    testing:
      needs: ['versioning']
      runs-on: ubuntu-latest
      steps:
        - run: echo "${{ vars.VERSION }}"
