name: Test

on: push

jobs:
    versioning:
        name: Test
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            
            - name: Another test
              uses: actions/github-script@v6
              with:
                script: |
                    // const exec = require('@actions/exec');
                    const files = await exec.exec('ls').then(f => f.toString().split('\n').filter(Boolean).map((dir) => ({ name: dir })))
                    
                    console.log(files);
